-- AlterTable
ALTER TABLE `Image` ADD COLUMN `mediaType` ENUM('SOURCE', 'COMPRESSED') NOT NULL DEFAULT 'SOURCE';

-- AlterTable
ALTER TABLE `Video` ADD COLUMN `mediaType` ENUM('SOURCE', 'COMPRESSED') NOT NULL DEFAULT 'SOURCE';
