// Generated by db
export interface IEntity {
  id: number;
  created_at: string;
  updated_at: string;
}

// Not exported yet, because i want to find bugs in changed code
export interface IItem {
  account_uid: string;

  private: boolean;
}

interface IWidthHeight {
  width: number;
  height: number;
}

interface IFileBasics {
  s3path: string;
  filesize: number;
}

export interface IFile extends IItem, IFileBasics {
  originalFilename: string;
}

export interface IVideo extends IItem, IWidthHeight, IFileBasics {
  originalFilename: string;
  processed: boolean;
  duration: number;
  bitrate: number;
}

export interface IImage extends IItem, IWidthHeight, IFileBasics {
  originalFilename: string;
  processed: boolean;
  isAnimated: boolean;
  hash: string;
}
