on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.12.1'

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v3

      - name: Debug - pwd / ls
        run: |
          pwd
          ls

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["env/.env.template"]'
        env:
          CDN: https://somecdn.com/...

      - name: SSH - Clear previous deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          # Remove all files inside of it, silence errors like "no files found to delete"
          script: rm -r ${{ secrets.FTP_DIST_DIR }}/* | exit 0


      - name: SFTP - Deploy website
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_HOST }}
          port: 22
          local_path: './*'
          remote_path: ${{ secrets.FTP_DIST_DIR }}/
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}


      
