on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.12.1'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: artifacts

      - name: Debug - pwd / ls
        run: |
          pwd
          ls -a artifacts

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["artifacts/.env.template"]'
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_KEY: ${{ secrets.FB_KEY }}
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          CORS_URL: ${{ secrets.CORS_URL }}

      - name: Rename .env.template to .env.production
        run: |
          mv artifacts/.env.template artifacts/.env.production
          tar -czvf artifacts.tar.gz artifacts

      - name: SSH - Ensure temp folder for upload
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            mkdir -p ${{ secrets.FTP_DIST_TEMP_DIR }}

      - name: SFTP - Deploy website
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_HOST }}
          port: 22
          local_path: './artifacts.tar.gz'
          remote_path: ${{ secrets.FTP_DIST_TEMP_DIR }}/
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}

      - name: SSH - Clear previous App and stop Services
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.FTP_DIST_TEMP_DIR }}/
            tar -xzvf artifacts.tar.gz
            rm artifacts.tar.gz
            cd artifacts
            yarn install
      
            cd /
            pm2 stop cerebro_api
            service mysql stop
            rm -r ${{ secrets.FTP_DIST_DIR }} | exit 0
            
            mv ${{ secrets.FTP_DIST_TEMP_DIR }}/artifacts ${{ secrets.FTP_DIST_DIR }} 
            cd ${{ secrets.FTP_DIST_DIR }}
            yarn prisma:deploy
            pm2 start cerebro_api
            service mysql start

            
